#!/bin/bash
dir='/home/vijay/Pictures/calvin'
file=`/bin/ls -1 "$dir" | sort --random-sort | head -1`
path=`readlink --canonicalize "$dir/$file"` # Converts to full path
echo "The randomly-selected wallpaper is: $path"
gsettings set org.gnome.desktop.background picture-uri file://$path
